language: haskell
ghc: 7.8
install:
  - cabal install purescript --force-reinstalls
  - sudo add-apt-repository ppa:chris-lea/node.js -y
  - sudo apt-get update -q
  - sudo apt-get install nodejs
  - npm install bower
notifications:
  email:
   - ttsujikawa@gmail.com
script:
  - npm install
  - bower install
  - bower prune
  - $(npm bin)/gulp example
  - npm run test
